{ lib }: {
  username = "th";
  userfullname = "Thigago Fraga";
  useremail = "a@a.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....Z8z4JM6UwSiQEq..cZzV6/$aCbEiHVPcgqCA82DjKIusqDwrVZ6qZ0mcF.QqGhWUU1";
  sshAuthorizedKeys = [
  ];

}
